import os

MAILCHIMP_API_KEY = os.environ.get('MAILCHIMP_API_KEY')
MAILCHIMP_LIST_ID = os.environ.get('MAILCHIMP_LIST_ID')
TEST_RECIPIENT_EMAIL = os.environ.get('TEST_RECIPIENT_EMAIL')
MANDRILL_API_KEY = os.environ.get('MANDRILL_API_KEY')
